# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm ci
      working-directory: integration-tests
    - name: Generate .env.local and .secret.local files
      run: |
          mkdir -p extensions
          echo "$ENV_LOCAL" >    extensions/auth-activity-feeds.env.local
          echo "$SECRET_LOCAL" > extensions/auth-activity-feeds.secret.local
          echo "$ENV_LOCAL" >    extensions/auth-chat.env.local
          echo "$SECRET_LOCAL" > extensions/auth-chat.secret.local
          echo "$ENV_LOCAL" >    extensions/firestore-activity-feeds.env.local
          echo "$SECRET_LOCAL" > extensions/firestore-activity-feeds.secret.local
      working-directory: integration-tests
      env:
        ENV_LOCAL : ${{secrets.ENV_LOCAL}}
        SECRET_LOCAL : ${{secrets.SECRET_LOCAL}}
    - run: npm test
      working-directory: integration-tests
      env:
        COLLECTION: feeds
